### ISSUE TITLE
Michel tag creates a diff in the file app/pim_parameters

### ISSUE THREAD

**Issue by grena** [akeneo/michel-tag#21]
When creating the PR to prepare the release, Michel Tag creates a diff in the `app/pim_parameters`:

```diff
     elasticsearch_index_configuration_files:
-        - '%kernel.root_dir%/../vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml'
+        - '%kernel.root_dir%/../src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml'
```

I don't know why, but I think it's a bug.

**Comment by juliensnz** [comment]
We always copy files from the dev to the std. So the path is not valid in the std file. There is no generic way to fix this so we will have to handle that with some custom code :/

**Comment by juliensnz** [comment]
fixed :)
