### ISSUE TITLE
Merging back the clean composer.json uses the user oAuth instead of configuration

### ISSUE THREAD

**Issue by SamirBoulil** [akeneo/michel-tag#5]
After tagging a version (creating the tag and pushing it into the repository), michel is reverting it's changes on the composer.json. At this step, it tries to push directly the 1.X branch onto the remote 1.X.

If you are not admin and if the branch is protected, there is no way michel tag successfully pushes those changes because these operations do not use the github API (PR/Merge PR).

@phaseinducer started some refacto to overcome this issue. I just document it here so that people understand if their release process does not work properly.

**Comment by aRn0D** [comment]
Done by https://github.com/akeneo/michel-tag/pull/9
